"""
Build env.yaml from .env for `gcloud run deploy --env-vars-file env.yaml`.

CRITICAL: NEVER use --set-env-vars with space-separated values for these
keys. That was RC2 — DEMO_SPACE_ID got concatenated into
DEFAULT_OPENPROJECT_API_KEY and broke production. Use --env-vars-file
exclusively.

Usage:
    python scripts/build_env_yaml.py
    # then review env.yaml, add any prod-only keys, and run:
    # gcloud run deploy ... --env-vars-file env.yaml

The output `env.yaml` is .gitignored. Never commit it.
"""
from __future__ import annotations

import os
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
ENV_FILE = REPO_ROOT / ".env"
OUT_FILE = REPO_ROOT / "env.yaml"


def parse_env(path: Path) -> dict[str, str]:
    """Return key=value pairs from a .env file, ignoring comments and blanks."""
    out: dict[str, str] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        out[key] = value
    return out


def quote_yaml_scalar(value: str) -> str:
    """Emit a YAML scalar that's safe even if it contains special characters."""
    # Reject newlines outright — that's RC2-style corruption.
    if "\n" in value or "\r" in value:
        raise SystemExit(f"FATAL: value contains newline/CR — refusing to emit. Value len={len(value)}")
    # Always double-quote and escape backslashes + double-quotes.
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def main() -> int:
    if not ENV_FILE.exists():
        print(f"ERROR: {ENV_FILE} not found.", file=sys.stderr)
        return 1

    env = parse_env(ENV_FILE)

    # Production-only keys that aren't in .env but Cloud Run needs.
    # Print a warning if missing so the operator can add them manually.
    PROD_ONLY = ("DEFAULT_OPENPROJECT_API_KEY", "DEMO_SPACE_ID")
    missing = [k for k in PROD_ONLY if k not in env]

    out_lines: list[str] = []
    out_lines.append("# env.yaml — generated by scripts/build_env_yaml.py")
    out_lines.append("# DO NOT COMMIT. Add to .gitignore.")
    out_lines.append("# Use with: gcloud run deploy ... --env-vars-file env.yaml")
    out_lines.append("")

    for key, value in env.items():
        out_lines.append(f"{key}: {quote_yaml_scalar(value)}")

    if missing:
        out_lines.append("")
        out_lines.append("# === PRODUCTION-ONLY KEYS — fill these in before deploy ===")
        for k in missing:
            out_lines.append(f'# {k}: "REPLACE_WITH_REAL_VALUE"')

    OUT_FILE.write_text("\n".join(out_lines) + "\n", encoding="utf-8")
    print(f"Wrote {OUT_FILE} with {len(env)} keys.")
    if missing:
        print(f"WARNING: production-only keys not in .env: {missing}")
        print(f"         Add them to env.yaml before running gcloud run deploy.")

    # Sanity-check: every emitted value is a single-line YAML scalar
    print()
    print("Validating output shape...")
    bad = []
    for line in out_lines:
        if line.startswith("#") or not line.strip():
            continue
        if not line.split(":", 1)[0].replace("_", "").replace("-", "").isalnum():
            bad.append(line)
        if line.count(":") < 1:
            bad.append(line)
    if bad:
        print("FAIL — these lines look malformed:")
        for b in bad:
            print(f"  {b}")
        return 1
    print(f"OK — {sum(1 for l in out_lines if l and not l.startswith('#'))} valid lines.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
